
version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_USER=testdb
      - POSTGRES_DB=testdb
    ports:
      - 5432:5432
    volumes:
      - ./config_pg/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./config_pg/students.csv:/tmp/students.csv

  admin:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres